name: Docker Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
    types: [closed]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: nxthongbk
          password: dckr_pat_kaeMIdxFIF0NVPS6vx82yGZo69k

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nxthongbk/securevision:develop


